name: CMake

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install gtest
      run: sudo apt install libgtest-dev lcov

    - name: build
      run: cmake -B ./build

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: install gtest
      run: sudo apt install libgtest-dev lcov
      
    - name: build
      run: cmake -Dtest=true -B ./build
      
    - name: make
      run: cmake --build ./build

    - name: run-tests
      run: ./build/Google_tests/Google_tests
      
    - name: get-stats
      run: lcov -t "tests" -o coverage.info -c -d . && genhtml -o report coverage.info
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
